### PR TITLE
Prefix internal events

### PR DESCRIPTION
**Pull request by SoAG**
Prefix internal events to avoid infinite loop when the match string contains the the event name.

### CODE REVIEW

**Comment by missinglink** [comment]
hey @SoAG 3 things I noted, from least important -> most important.

1. Should we completely upper-case 'HUNTSMAN_response' -> 'HUNTSMAN_RESPONSE', this is completely subjective and makes my ODC tingle, your thoughts?

2. I worries me greatly that the internal API changed significantly and yet no unit tests failed, I guess no-one is to blame there except myself.

3. In particular I would have expected this test to fail? https://github.com/SoAG/huntsman/blob/prefix-internal-events/test/huntsman.coffee#L23

**Comment by SoAG** [comment]
Yes, was surprised too that all the tests just passed. I'll capitalise all the events and take a look at the tests tonight.

**Comment by SoAG** [comment]
Hi @missinglink,

So I've capitalised all the internal events which in turn made the test you mentioned fail. It was a mistake on my side cause it could still match the lower cased `exit` in `HUNTSMAN_exit` when the event was emitted, now with all internal events being upper case it works as expected. Let me know what you think.

**Comment by missinglink** [comment]
This is great @SoAG thanks for putting in the time, I'm happy to merge this as-is.

```bash
$ npm publish
npm http PUT https://registry.npmjs.org/huntsman
npm http 201 https://registry.npmjs.org/huntsman
+ huntsman@0.2.12
```

**Comment by missinglink** [comment]
If you have any ideas for changing `regexemitter` I'd be happy to discuss an issue or PR on that repo

**Comment by missinglink** [comment]
resolves https://github.com/missinglink/huntsman/issues/12

**Comment by SoAG** [comment]
Awesome thanks a lot.

**Pull request merged**
